name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: hotel-management-backend
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
        echo "✅ Dependencies installed successfully"

    - name: Generate ML models
      run: |
        echo "🔧 Generating ML models..."
        python generate_ml_models.py
        echo "✅ ML models generated successfully"

    - name: Test application import
      run: |
        echo "🧪 Testing application import..."
        python -c "from app.main import app; print('✅ Application imports successfully')"
        echo "✅ Application import test passed"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Health check
      run: |
        echo "Deployment completed. Checking health..."
        sleep 30
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health || echo "Health check failed - app may still be starting"
